
spring:
  datasource:
    url: ${MARKET_DB_JDBC_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:market_db}}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  r2dbc:
    url: ${MARKET_DB_R2DBC_URL:r2dbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:market_db}}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  liquibase:
    url: ${MARKET_DB_JDBC_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/${POSTGRES_DB:market_db}}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    change-log: classpath:lq/db.changelog-master.xml

  messages:
    basename: messages
    encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          payment-service:
            provider: keycloak
            client-id: ${MARKET_OAUTH_CLIENT_ID:market-app}
            client-secret: ${MARKET_OAUTH_CLIENT_SECRET:market-app-secret}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:${KEYCLOAK_PORT:8003}/realms/${KEYCLOAK_REALM:market}/protocol/openid-connect/token}

server:
  error:
    whitelabel:
      enabled: false
  port: 8088

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.web.reactive.result.method.annotation: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
