services:

  postgres:
    image: postgres:16

    container_name: my-market-postgres

    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7
    container_name: my-market-redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: my-market-keycloak
    command: start-dev --import-realm
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8003"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    restart: unless-stopped

  app:
    build: .
    container_name: mymarket-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
