spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  error:
    whitelabel:
      enabled: false